### ISSUE TITLE
me saca al solicitar reportes

### ISSUE THREAD

**Issue by afconstructiva** [efdiloreto/Zonda#1]
Hola Eduardo, estoy probando el programa y sea cual sea la opción de carga que calculo te saca del programa al pedir los reportes, por lo demás encuentro que esta aplicando las cargas de manera coherente, al menos con los cálculos que hice manualmente

**Comment by efdiloreto** [comment]
Hola, te recomiendo usar este repo. https://github.com/efdiloreto/ZondaPro

**Comment by afconstructiva** [comment]
Efectivamente esta descarga es la que he utilizado, y el programa funciona correctamente, pero cuando pido cualquier reporte, automaticamente me saca del programa

Te paso video tal vez te ayude a entenderlo





De: Eduardo Di Loreto ***@***.***>
Enviado: lunes, 18 de marzo de 2024 21:34
Para: efdiloreto/Zonda ***@***.***>
Cc: afconstructiva ***@***.***>; Author ***@***.***>
Asunto: Re: [efdiloreto/Zonda] me saca al solicitar reportes (Issue #1)


Hola, te recomiendo usar este repo. https://github.com/efdiloreto/ZondaPro

**Comment by efdiloreto** [comment]
Esto debería solucionarlo

https://github.com/efdiloreto/ZondaPro/issues/4

**Comment by afconstructiva** [comment]
Excelente Eduardo, anda perfecto

gracias por tu aportacion

Ariel
________________________________
De: Eduardo Di Loreto ***@***.***>
Enviado: martes, 19 de marzo de 2024 3:11
Para: efdiloreto/Zonda ***@***.***>
Cc: afconstructiva ***@***.***>; Author ***@***.***>
Asunto: Re: [efdiloreto/Zonda] me saca al solicitar reportes (Issue #1)


Esto debería solucionarlo

efdiloreto/ZondaPro#4<https://github.com/efdiloreto/ZondaPro/issues/4>
